# Generated by Django 4.2.6 on 2024-04-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_moneda',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
